//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportTemperature.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImportTemperature.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алейск  12428
        ///Алтайское  12438
        ///Баево  126070
        ///Барнаул  4720
        ///Барнаул (а/п)  12995
        ///Новосиликатный  12433
        ///Южный  12432
        ///Белокуриха  11427
        ///Бийск (а/п)  12997
        ///Бийск  4731
        ///Амурский  126101
        ///Благовещенка  12435
        ///Бурла  126160
        ///Быстрый Исток  126183
        ///Волчиха  12442
        ///Новоегорьевское  126211
        ///Ельцовка  126226
        ///Завьялово  126242
        ///Залесово  126259
        ///Заринск  12429
        ///Змеиногорск  5178
        ///Андреевский  126311
        ///Бийск-Зональная  4730
        ///Зональное  126337
        ///Калманка  126359
        ///Аллак  126373
        ///Камень-на-Оби  4718
        ///Ключи  126408 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
    }
}
